// Document Set Data - This would typically come from an API
export const documentSets = [
  {
    setId: 'DS-00123',
    vendor: 'Acme Corporation',
    poNumber: 'PO-2024-0456',
    status: 'Ready for Verification',
    documents: { invoice: true, po: true, grn: false },
    totalAmount: 12345.67,
    statusType: 'ready-for-review',
    priority: 'high',
    majorIssues: 2,
    minorIssues: 1,
    daysInQueue: 8,
    assignedTo: 'John Smith',
    lastActivity: '2024-01-16'
  },
  {
    setId: 'DS-00124',
    vendor: 'Tech Solutions Ltd',
    poNumber: 'PO-2024-0457',
    status: 'Ready for Verification',
    documents: { invoice: true, po: true, grn: false },
    totalAmount: 8976.42,
    statusType: 'ready-for-review',
    priority: 'medium',
    majorIssues: 0,
    minorIssues: 2,
    daysInQueue: 5,
    assignedTo: 'Sarah Johnson',
    lastActivity: '2024-01-17'
  },
  {
    setId: 'DS-00125',
    vendor: 'Office Supplies Co',
    poNumber: 'PO-2024-0458',
    status: 'Ready for Verification',
    documents: { invoice: true, po: true, grn: true },
    totalAmount: 5432.18,
    statusType: 'ready-for-review',
    priority: 'low',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 2,
    assignedTo: 'Mike Davis',
    lastActivity: '2024-01-18'
  },
  {
    setId: 'DS-00126',
    vendor: 'Industrial Parts Inc',
    poNumber: 'PO-2024-0459',
    status: 'Missing Documents',
    documents: { invoice: true, po: false, grn: false },
    totalAmount: 15678.90,
    statusType: 'incomplete',
    priority: 'high',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 10,
    assignedTo: null,
    lastActivity: '2024-01-15'
  },
  {
    setId: 'DS-00127',
    vendor: 'Quick Supply Co',
    poNumber: 'PO-2024-0460',
    status: 'Verified',
    documents: { invoice: true, po: true, grn: true },
    totalAmount: 3245.12,
    statusType: 'auto-approved',
    priority: 'low',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 1,
    assignedTo: 'Lisa Brown',
    lastActivity: '2024-01-18'
  },
  {
    setId: 'DS-00128',
    vendor: 'Beta Solutions Inc',
    poNumber: 'PO-2024-0461',
    status: 'Verified',
    documents: { invoice: true, po: true, grn: true },
    totalAmount: 7432.50,
    statusType: 'auto-approved',
    priority: 'medium',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 0,
    assignedTo: 'Emma Wilson',
    lastActivity: '2024-01-20'
  },
  {
    setId: 'DS-00136',
    vendor: 'Alpha Manufacturing',
    poNumber: 'PO-2024-0470',
    status: 'Ready for Verification',
    documents: { invoice: true, po: true, grn: false },
    totalAmount: 18976.33,
    statusType: 'ready-for-review',
    priority: 'high',
    majorIssues: 1,
    minorIssues: 3,
    daysInQueue: 6,
    assignedTo: 'Alex Chen',
    lastActivity: '2024-01-19'
  },
  {
    setId: 'DS-00137',
    vendor: 'Processing Test Corp',
    poNumber: 'PO-2024-0471',
    status: 'Processing Failed',
    documents: { invoice: true, po: true, grn: false },
    totalAmount: 9876.54,
    statusType: 'processing-failed',
    priority: 'high',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 4,
    assignedTo: 'System Admin',
    lastActivity: '2024-01-20'
  },
  {
    setId: 'DS-00129',
    vendor: 'Processing Test Corp',
    poNumber: 'PO-2024-0472',
    status: 'Processing Failed',
    documents: { invoice: true, po: true, grn: false },
    totalAmount: 7654.32,
    statusType: 'processing-failed',
    priority: 'high',
    majorIssues: 0,
    minorIssues: 0,
    daysInQueue: 3,
    assignedTo: 'System Admin',
    lastActivity: '2024-01-20'
  }
];

export const getDocumentSetById = (setId: string) => {
  return documentSets.find(set => set.setId === setId);
};